#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
"""Offline builder for the gfx1250 pre-compiled kernels (kernel_tag a16w16_4wave_co).

Why this exists
---------------
The 4wave_compute pipeline needs things a release ROCm toolchain does not have:

  * ``__builtin_amdgcn_pin_vgpr`` and ``amdgpu_num_vgpr(N)`` -- the register
    placement request the kernel's whole schedule is built around. Stock ROCm
    does not know the builtin at all.
  * ``-mllvm -amdgpu-expert-scheduling-mode`` -- stock ROCm rejects it outright,
    and aiter's JIT ``hip_flag_checker`` SILENTLY DROPS rejected flags, so a JIT
    build would not fail loudly, it would quietly mis-schedule.
  * gfx1250's v256-v1023 register file.

So this kid's device code is compiled ahead of time, here, and loaded at runtime
by ``include/gfx1250/opus_co_launch_gfx1250.cuh``. Everything else about the kid
goes through the ordinary JIT path.

Source of truth
---------------
``gen_co/co_kernels.json`` -- read by ``opus_gemm_common.py`` to build the kid
table (which drives the JIT codegen) and re-read from there by this script. One
file describes each variant's tile, cluster, launch bounds, VGPR budget, dtypes
and device flags, so adding a variant never touches Python. Both sides spell the
traits through ``co_traits_args()``, which is what makes the three names
identical without any sidecar::

    .co filename == extern "C" symbol inside the .co == host launcher symbol

The compiler is NOT pinned to a version
---------------------------------------
``--llvm-bin`` just says which toolchain to use; nothing here checks what it is.
The resolved clang, its version and each entry's exact flags are recorded in
``build_info.json`` -- when behaviour changes after a toolchain bump, that
record plus the emitted assembly (``asm/*.s`` and ``asm/*.dis``) is how you find
out why.

Usage
-----
::

    python3 csrc/opus_gemm/gen_co/build_co.py --llvm-bin /path/to/llvm/build/bin

    # or via the environment
    OPUS_CO_LLVM_BIN=/path/to/llvm/build/bin \\
    python3 csrc/opus_gemm/gen_co/build_co.py

``HIP_CLANG_PATH`` is how hipcc is pointed at another clang, so the driver flags
stay identical whichever toolchain is selected.
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

_HERE = os.path.dirname(os.path.abspath(__file__))
_OPUS_GEMM_DIR = os.path.dirname(_HERE)  # csrc/opus_gemm
_CSRC_DIR = os.path.dirname(_OPUS_GEMM_DIR)  # csrc

# opus_gemm_common / codegen.* are imported the same way gen_instances.py does.
sys.path.insert(0, _OPUS_GEMM_DIR)

from codegen.gen_instances_gfx1250 import (
    KARGS_NAME_MAP,
    KERNEL_FUNC_MAP,
    TRAITS_NAME_MAP,
    co_traits_args,
)

# The _declared_ table, not the filtered one: opus_gemm_common drops entries
# whose .co is not on disk (so nothing downstream can register an unlaunchable
# kid), and this script exists to create exactly those files.
from opus_gemm_common import gfx1250_4wave_co_kernels_declared

# Every pre-compiled family and the pipeline header each one's device body
# lives in. The rest of the stub (traits/kargs/body names) comes from the
# codegen maps, so a new family is one row here plus one row there.
_PIPELINE_HEADERS = {
    "a16w16_4wave_co": "opus_gemm_pipeline_a16w16_4wave_compute_gfx1250.cuh",
    "a16w16_4wave_wl_co": "opus_gemm_pipeline_a16w16_4wave_wl_gfx1250.cuh",
}

# Stub TU. Mirrors the standalone kernel's own stub: the host pass gets an empty
# body (so hipcc's two-pass compile has a definition on both sides) and only the
# device pass pulls in the pipeline.
#
# The attributes live HERE, on the extern "C" wrapper, not on the __device__
# body -- they describe the kernel entry point. extern "C" is what makes the
# symbol name predictable enough to equal the filename.
#
# __cluster_dims__ is defined by hip_minimal only under __gfx1250__, i.e. only
# on the device pass; the declaration below is parsed on both, so define it for
# the host pass too (same workaround the JIT host TU uses).
_STUB_TEMPLATE = """// SPDX-License-Identifier: MIT
// Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
//
// Auto-generated by csrc/opus_gemm/gen_co/build_co.py. Do not edit or commit.
#include "gfx1250/opus_gemm_traits_a16w16_gfx1250.cuh"

#ifdef __HIP_DEVICE_COMPILE__
#include "gfx1250/{pipeline_header}"
#endif

#ifndef __cluster_dims__
#define __cluster_dims__(...) __attribute__((cluster_dims(__VA_ARGS__)))
#endif

// amdgpu_num_vgpr is a device-side codegen directive; asking for it on the host
// pass only earns an "attribute ignored" diagnostic.
#if defined(__HIP_DEVICE_COMPILE__) && {want_num_vgpr}
#define OPUS_CO_NUM_VGPR __attribute__((amdgpu_num_vgpr({num_vgpr})))
#else
#define OPUS_CO_NUM_VGPR
#endif

using CoTraits = {traits_name}<{traits_args}>;

extern "C" __global__ __launch_bounds__({lb_threads}, {lb_waves})
OPUS_CO_NUM_VGPR
__cluster_dims__({cwm}, {cwn}, 1)
void {symbol}({kargs_name} kargs)
{{
#ifdef __HIP_DEVICE_COMPILE__
    {body_func}<CoTraits>(kargs);
#else
    (void)kargs;
#endif
}}
"""

_BUNDLE_MAGIC = b"__CLANG_OFFLOAD_BUNDLE__"


def _run(cmd, **kw):
    return subprocess.run(cmd, check=True, capture_output=True, text=True, **kw)


def _tool(llvm_bin, name, fallback_env=None):
    """Resolve an LLVM tool, preferring the selected toolchain so the metadata
    reader and the disassembler are the same version as the compiler -- a older
    llvm-objdump cannot decode gfx1250's newer opcodes."""
    if llvm_bin:
        cand = os.path.join(llvm_bin, name)
        if os.path.exists(cand):
            return cand
    if fallback_env and os.environ.get(fallback_env):
        return os.environ[fallback_env]
    found = shutil.which(name)
    if found:
        return found
    raise SystemExit(f"build_co: cannot find {name} (pass --llvm-bin)")


def _unbundle_if_needed(path, llvm_bin, arch):
    """--genco may emit a clang offload bundle; AiterAsmKernelFast hands the
    bytes straight to __hipRegisterFatBinary and needs a bare amdhsa ELF."""
    with open(path, "rb") as f:
        head = f.read(len(_BUNDLE_MAGIC))
    if head != _BUNDLE_MAGIC:
        return False
    bundler = _tool(llvm_bin, "clang-offload-bundler")
    tmp = path + ".unbundled"
    _run(
        [
            bundler,
            "--unbundle",
            "--type=o",
            f"--targets=hipv4-amdgcn-amd-amdhsa--{arch}",
            f"--input={path}",
            f"--output={tmp}",
        ]
    )
    os.replace(tmp, path)
    return True


def _kernel_metadata(readelf, path, symbol):
    """Pull (.vgpr_count, .sgpr_count, .group_segment_fixed_size,
    .kernarg_segment_size) for `symbol` out of the AMDGPU note."""
    out = _run([readelf, "--notes", path]).stdout
    # One kernel per .co, so a flat scan is enough -- but assert that, because
    # a second kernel would make the numbers ambiguous.
    names = re.findall(r"^\s*\.name:\s*(\S+)\s*$", out, re.MULTILINE)
    if names != [symbol]:
        raise SystemExit(
            f"build_co: {os.path.basename(path)} should contain exactly one "
            f"kernel named {symbol!r}, found {names!r}"
        )
    fields = {}
    for key in (
        "vgpr_count",
        "sgpr_count",
        "vgpr_spill_count",
        "sgpr_spill_count",
        "group_segment_fixed_size",
        "kernarg_segment_size",
    ):
        m = re.search(rf"^\s*\.{key}:\s*(\d+)\s*$", out, re.MULTILINE)
        if m is None:
            raise SystemExit(f"build_co: .{key} missing from {path} metadata")
        fields[key] = int(m.group(1))
    return fields


def _expected_lds(k, no_pad=False):
    """Mirror of the traits LDS formula (kLdsTotalBytes).

    Including the 1-WG/CU pad: a tile whose A/B segments fit twice in the
    320 KB budget is padded past 160 KB so a second workgroup cannot co-reside.
    Keep this in step with LDS_BYTES in the traits -- the check below compares
    the two and is the reason the drift was caught rather than shipped.

    ``no_pad`` mirrors -DOPUS_CO_NO_1WG_PAD, the debug switch that puts the
    padded variants back at 2 WG/CU.
    """
    pitch = k.B_K + 16 // 2  # + PAD_ELEMS for bf16
    seg = k.num_slots * (k.B_M + k.B_N) * pitch * 2
    half = 160 * 1024
    if no_pad:
        return seg
    return (half + 1024) if seg <= half else seg


# A WMMA destination prints as the ENCODED register plus a comment holding the
# physical one the pin produced:
#     v_wmma_f32_16x16x32_bf16 v[0:7] /*v[256:263]*/, ...
# The comment is the number that matters; without a pin there is no comment and
# the encoded operand is the physical register.
_WMMA_DST = re.compile(r"v_wmma\S*\s+v\[(\d+):\d+\]\s*(?:/\*v\[(\d+):)?")


def _asm_stats(text, prefix):
    """The numbers that used to be enforced by --min-vgpr, now RECORDED instead
    of judged: with several VGPR budgets in the table there is no single
    threshold that means "the pin was honoured". Compare them across builds.

    va_vdst(0) counts the full VALU->VMEM drains the pinning exists to avoid
    (21 in the pinned reference, 160 unpinned); wmma_dst_hi says whether the
    accumulators actually landed in the high register file (768/768 pinned,
    0/768 unpinned).
    """
    lines = text.splitlines()
    hi = total = 0
    for ln in lines:
        m = _WMMA_DST.search(ln)
        if not m:
            continue
        total += 1
        dst = int(m.group(2) or m.group(1))
        if 256 <= dst <= 511:
            hi += 1
    return {
        f"{prefix}lines": len(lines),
        f"{prefix}va_vdst0": sum(1 for ln in lines if "va_vdst(0)" in ln),
        f"{prefix}wmma": total,
        f"{prefix}wmma_dst_hi": hi,
    }


def build_one(k, args, llvm_bin, workdir):
    symbol = k.name
    no_pad = "-DOPUS_CO_NO_1WG_PAD" in args.device_flag
    stub_path = os.path.join(workdir, f"{symbol}.cc")
    with open(stub_path, "w") as f:
        f.write(
            _STUB_TEMPLATE.format(
                pipeline_header=_PIPELINE_HEADERS[k.kernel_tag],
                traits_name=TRAITS_NAME_MAP[k.kernel_tag],
                traits_args=co_traits_args(k),
                kargs_name=KARGS_NAME_MAP[k.kernel_tag],
                body_func=KERNEL_FUNC_MAP[k.kernel_tag],
                symbol=symbol,
                lb_threads=k.BLOCK_SIZE,
                lb_waves=k.co_min_waves_per_eu,
                want_num_vgpr=1 if k.co_num_vgpr else 0,
                num_vgpr=k.co_num_vgpr or 0,
                cwm=k.cluster_wg_m,
                cwn=k.cluster_wg_n,
            )
        )

    out_path = os.path.join(args.out_dir, f"{symbol}.co")
    device_flags = list(k.co_device_flags) + list(args.device_flag)
    # Everything except the output mode and the input, so the -S pass below is
    # byte-for-byte the same compilation.
    common = [
        *args.hipcc.split(),
        "-x",
        "hip",
        f"--offload-arch={args.arch}",
        "-std=c++20",
        "-O3",
        # Skips the implicit __clang_hip_runtime_wrapper.h on the host pass. It
        # also keeps the kernel free of HIP's hidden/implicit kernargs, which is
        # what lets the runtime launch it through HIP_LAUNCH_PARAM_BUFFER_POINTER
        # like the hand-written asm .co files.
        "-D__HIPCC_RTC__",
        f"-I{_CSRC_DIR}/include",
        f"-I{_OPUS_GEMM_DIR}/include",
        *device_flags,
    ]
    env = dict(os.environ)
    if llvm_bin:
        env["HIP_CLANG_PATH"] = llvm_bin

    def run_compile(extra, out, what):
        proc = subprocess.run(
            [*common, *extra, "-o", out, stub_path],
            capture_output=True,
            text=True,
            env=env,
            # The failure path prints hipcc's own diagnostics before exiting;
            # CalledProcessError would hide them behind a traceback.
            check=False,
        )
        if proc.returncode != 0:
            sys.stderr.write(proc.stdout)
            sys.stderr.write(proc.stderr)
            raise SystemExit(f"build_co: hipcc failed for {symbol} ({what})")
        if proc.stderr.strip():
            # Warnings are worth seeing: a dropped attribute here is exactly the
            # failure mode this whole offline path exists to avoid.
            sys.stderr.write(proc.stderr)

    print(f"[build_co] compiling {symbol}")
    run_compile(["--genco"], out_path, "genco")

    unbundled = _unbundle_if_needed(out_path, llvm_bin, args.arch)

    readelf = _tool(llvm_bin, "llvm-readelf")
    md = _kernel_metadata(readelf, out_path, symbol)

    # Self-checks. Only the two that would make the HOST wrong are fatal; see
    # --fail-on-spill and _asm_stats() for the ones that merely describe the
    # code generated.
    want_lds = _expected_lds(k, no_pad)
    if md["group_segment_fixed_size"] != want_lds:
        raise SystemExit(
            f"build_co: {symbol} LDS mismatch: .co says "
            f"{md['group_segment_fixed_size']}, traits say {want_lds}"
        )
    if md["vgpr_spill_count"] or md["sgpr_spill_count"]:
        msg = (
            f"{symbol} spills (vgpr={md['vgpr_spill_count']}, "
            f"sgpr={md['sgpr_spill_count']})"
        )
        if args.fail_on_spill:
            raise SystemExit(f"build_co: {msg} and --fail-on-spill is set")
        # Expected at the tighter VGPR budgets, so a warning: the counts are in
        # build_info.json for whoever is sweeping them.
        print(f"[build_co]   WARNING: {msg}", file=sys.stderr)

    info = {
        "symbol": symbol,
        "kid": next(
            kid for kid, v in gfx1250_4wave_co_kernels_declared.items() if v is k
        ),
        "tile": [k.B_M, k.B_N, k.B_K],
        "cluster": [k.cluster_wg_m, k.cluster_wg_n],
        "num_slots": k.num_slots,
        "launch_bounds": [k.BLOCK_SIZE, k.co_min_waves_per_eu],
        "num_vgpr_requested": k.co_num_vgpr,
        "device_flags": device_flags,
        "traits_args": co_traits_args(k),
        **md,
    }

    if not args.no_asm:
        asm_dir = os.path.join(args.out_dir, "asm")
        os.makedirs(asm_dir, exist_ok=True)
        # (1) the compiler's own listing: .amdhsa_* directives, waitcnt and
        # register-allocation comments. Same flags, same clang, so it describes
        # the .co next to it -- but it IS a second compilation.
        s_path = os.path.join(asm_dir, f"{symbol}.s")
        run_compile(["-S", "--cuda-device-only"], s_path, "-S")
        # (2) the disassembly of the artifact that actually ships. When (1) and
        # (2) disagree, this one is the truth.
        objdump = _tool(llvm_bin, "llvm-objdump")
        dis = _run([objdump, "-d", f"--mcpu={args.arch}", out_path]).stdout
        dis_path = os.path.join(asm_dir, f"{symbol}.dis")
        with open(dis_path, "w") as f:
            f.write(dis)
        info["asm"] = {
            "s": os.path.relpath(s_path, args.out_dir),
            "dis": os.path.relpath(dis_path, args.out_dir),
        }
        # Both, because they count different things: the listing carries the
        # directives and scheduling comments (and is what the historical
        # 6463-line / 21 va_vdst(0) / 768 WMMA reference numbers came from),
        # while the disassembly is the artifact that actually ships.
        with open(s_path) as f:
            info.update(_asm_stats(f.read(), "asm_"))
        info.update(_asm_stats(dis, "dis_"))

    print(
        f"[build_co]   {symbol}: VGPR={md['vgpr_count']} SGPR={md['sgpr_count']} "
        f"LDS={md['group_segment_fixed_size']} kernarg={md['kernarg_segment_size']} "
        f"{'(unbundled)' if unbundled else '(bare ELF)'}"
    )
    return info


def main():
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument(
        "--hipcc",
        default=os.environ.get("HIPCC", "/opt/rocm/bin/hipcc"),
        help="hipcc driver (may include a leading `env ...`); default /opt/rocm/bin/hipcc",
    )
    p.add_argument(
        "--llvm-bin",
        "--pin-llvm-bin",  # old spelling, kept working
        dest="llvm_bin",
        default=os.environ.get("OPUS_CO_LLVM_BIN", os.environ.get("PIN", "")),
        help="bin/ of the LLVM build to compile with; exported as "
        "HIP_CLANG_PATH and used for llvm-readelf / llvm-objdump / "
        "clang-offload-bundler. No version is assumed or checked -- what "
        "was used is recorded in build_info.json. "
        "Defaults to $OPUS_CO_LLVM_BIN, then $PIN.",
    )
    p.add_argument("--arch", default="gfx1250")
    p.add_argument(
        "--device-flag",
        action="append",
        default=[],
        metavar="FLAG",
        help="extra device-pass flag appended to EVERY entry, repeatable. For "
        "investigations that need the whole family rebuilt one way, e.g. "
        "--device-flag=-DOPUS_CO_NO_1WG_PAD to drop the 1-WG/CU pad and "
        "put the affected variants back at 2 WG/CU. Recorded per entry in "
        "build_info.json, so an artifact never hides which one built it.",
    )
    p.add_argument(
        "--out-dir",
        default="",
        help="default: <this dir>/<arch>",
    )
    p.add_argument(
        "--no-asm",
        action="store_true",
        help="skip the asm/<symbol>.s and asm/<symbol>.dis debug dumps",
    )
    p.add_argument(
        "--fail-on-spill",
        action="store_true",
        help="treat any VGPR/SGPR spill as an error. Off by default: at the "
        "tighter VGPR budgets spilling is the expected outcome, not a "
        "malfunction. The counts always land in build_info.json.",
    )
    p.add_argument(
        "--jobs",
        "-j",
        type=int,
        default=max(1, (os.cpu_count() or 2) // 8),
        help="parallel hipcc invocations. Each takes ~1 core for ~3 s, so the "
        "default is deliberately well under nproc; a full sweep is thousands "
        "of entries and serial is hours.",
    )
    p.add_argument("--keep-temps", action="store_true")
    args = p.parse_args()

    if not args.out_dir:
        args.out_dir = os.path.join(_HERE, args.arch)
    os.makedirs(args.out_dir, exist_ok=True)

    llvm_bin = os.path.abspath(args.llvm_bin) if args.llvm_bin else ""
    print(f"[build_co] clang from: {llvm_bin or '(PATH / hipcc default)'}")

    instances = [
        k
        for k in gfx1250_4wave_co_kernels_declared.values()
        if k.kernel_tag in _PIPELINE_HEADERS
    ]
    if not instances:
        raise SystemExit(
            "build_co: no pre-compiled entries -- check gen_co/co_kernels.json"
        )

    workdir = tempfile.mkdtemp(prefix="opus_build_co_")
    try:
        if args.jobs == 1:
            built = [build_one(k, args, llvm_bin, workdir) for k in instances]
        else:
            # One hipcc per entry and they share nothing but the read-only headers,
            # so this is embarrassingly parallel. A full sweep is thousands of
            # entries; serially that is hours, and the box has hundreds of cores.
            # Threads, not processes: every worker spends its life in subprocess.
            from concurrent.futures import ThreadPoolExecutor

            print(f"[build_co] {len(instances)} entries on {args.jobs} jobs")
            with ThreadPoolExecutor(max_workers=args.jobs) as pool:
                built = list(
                    pool.map(lambda k: build_one(k, args, llvm_bin, workdir), instances)
                )
            built.sort(key=lambda b: b["kid"])
    finally:
        if args.keep_temps:
            print(f"[build_co] stub TUs kept in {workdir}")
        else:
            shutil.rmtree(workdir, ignore_errors=True)

    # Reproducibility record: which compiler and which flags produced these, so
    # "it behaves differently after a toolchain bump" is answerable. This record
    # is what replaces the removed --min-vgpr check.
    ver = ""
    try:
        clang = os.path.join(llvm_bin, "clang") if llvm_bin else "clang"
        ver = _run([clang, "--version"]).stdout.strip().splitlines()[0]
    except Exception:  # noqa: BLE001
        ver = "unknown"
    info = {
        "arch": args.arch,
        "hipcc": args.hipcc,
        "device_clang": ver,
        "hip_clang_path": llvm_bin,
        # Shared by every entry; the per-entry -mllvm flags are in kernels[].
        "common_flags": ["-D__HIPCC_RTC__", "-O3", "-std=c++20"],
        "kernels": built,
    }
    info_path = os.path.join(args.out_dir, "build_info.json")
    with open(info_path, "w") as f:
        json.dump(info, f, indent=2, sort_keys=True)
        f.write("\n")
    print(f"[build_co] wrote {len(built)} .co + {info_path}")


if __name__ == "__main__":
    main()
